### ISSUE TITLE
Py4JJavaError: An error occurred while calling o562.saveAsTextFile. : org.apache.spark.SparkException: Job aborted.

### ISSUE THREAD

**Issue by minji-o-j** [minji-o-j/Big-Data-Analytics#3]

**Comment by minji-o-j** [comment]
관리자권한 -> 안됨

**Comment by minji-o-j** [comment]
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 27.0 failed 1 times, most recent failure: Lost task 0.0 in stage 27.0 (TID 27, DESKTOP-GVCB5SU, executor driver): java.io.IOException: (null) entry in command string: null chmod 0644 C:\Users\user\Bigdata\data\ds_spark_wiki_out\_temporary\0\_temporary\attempt_20200919180749_0044_m_000000_0\part-00000
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:773)

Caused by: java.io.IOException: (null) entry in command string: null chmod 0644 C:\Users\user\Bigdata\data\ds_spark_wiki_out\_temporary\0\_temporary\attempt_20200919180749_0044_m_000000_0\part-00000
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:773)

**Comment by minji-o-j** [comment]
spark 설치 및 경로 설정 후 해결
참고
https://jjangjjong.tistory.com/24
